call bin\main.exe samples\Basic.jai
call bin\main.exe samples\Build.jai
call bin\main.exe samples\demo.jai
call bin\main.exe samples\File.jai
call bin\main.exe samples\GL.jai
call bin\main.exe samples\Math.jai
call bin\main.exe samples\Mixer.jai
call bin\main.exe samples\Mixer_Win32.jai
call bin\main.exe samples\Pool.jai
call bin\main.exe samples\Preload.jai
call bin\main.exe samples\Print.jai
call bin\main.exe samples\stb_image.jai
call bin\main.exe samples\Thread.jai
call bin\main.exe samples\Wav_File.jai
