/*
*
* DO NOT EDIT THIS FILE . This File is generated by "generator.py"
*
*/

enum class ETOKEN : u64 {
    ZERO = 0,
    IDENT = 256,
    KEYWORD,
    LITERAL,
    COMMENT,
    MULTILINE_COMMENT,
    COLON,
    DOUBLECOLON,
    COLONEQUAL,
    OPERATOR,
    DIRECTIVE,
    NONE,
    EOFA,
    ERROR,
};
