import os

a  = '/*\n*\n* DO NOT EDIT THIS FILE . This File is generated by "generator.py"\n*\n*/\n\n'

TokenTypes = {
	 "ZERO" : [True, 0]  ,
	 "IDENT" : [True, 256]  ,
	 "KEYWORD" : [False, 0]  ,
	 "LITERAL" : [False, 0]  ,
	 "COMMENT" : [False, 0]  ,
	 "MULTILINE_COMMENT" : [False, 0]  ,
	 "COLON" : [False, 0] ,
	 "DOUBLECOLON" : [False, 0] ,
	 "COLONEQUAL" : [False, 0] ,
	 "OPERATOR" : [False, 0] ,
	 "DIRECTIVE" : [False, 0] ,
	 "NONE" : [False, 0],
	 "EOFA" : [False, 0] ,
	 "ERROR" : [False, 0]
}

def generateEnum(file, enumName, enumtype, enumValues):
	file.write('enum class ' +  enumName + " : " + enumtype + ' {\n')
	for token, value in enumValues.items():
		file.write("    ")
		file.write(token)
		if value[0] != False:
			file.write(" = " + str(value[1]))
		file.write(",\n")
	file.write('};\n')

	
	
def generateFile() :
	file = open("constants.h", 'w')
	file.write(a)
	generateEnum(file, "ETOKEN" , "u64", TokenTypes) 	
	file.close()
	
generateFile()
